#!/bin/bash
echo Hello World    

git status

git add NPRs_Python_ResourceNotes.*
git add NPRs_Python_ResourceNotes_Pandas.*
git add Coursera.*

git commit -m "Updating Python (and Pandas) notes..."

git push
